services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: npm run dev
    env_file:
      - ./client/.env.local
    depends_on:
      server:
        condition: service_healthy

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./server/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  supabase:
    image: supabase/postgres:15.1.0.41
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 2rosFPxAIQPVRaej
      POSTGRES_DB: supabase
    volumes:
      - supabase_data:/var/lib/postgresql/data

  supabase-studio:
    image: supabase/studio:2025.10.20-sha-5005fc6
    ports:
      - "3001:3000"
    environment:
      SUPABASE_URL: http://supabase:5432
      SUPABASE_DB_USER: postgres
      SUPABASE_DB_PASSWORD: 2rosFPxAIQPVRaej
    depends_on:
      - supabase

volumes:
  supabase_data: